services:
  ws-backend:
    build:
      context: /backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/code:/code
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"